language: php

sudo: false

php:
  - "5.6"

  env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=expected.value29@gmail.com
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=expected.value29@gmail.com
    - secure: "ID2yngB1ctbLdo9PXHh/3wktm2Z57lD+J35OluzIbRGP9E/lzYm1eHjUglpl3od3rzuMHz3te/GbI7j/bWKSwoVevvc98IQcMnREJGD/VSI1qviaSgyiSjwIDfgMAmseg7J7uxIqnogv3zxk78rr1I+jifrxHaRejgKLMA54Ew/z5VMTw1yExpGzb0XfHuInkksECpgJpHc8HXKI+sdXy0PaRduLjmKwcynJKyEka22uav9m4Io37phX7YttqCcdccVOby+J802kJ/ubRMS1lTSWESRoIeev/5hWuud8XxaK0n4jnzCZ/9tYEK4obNBHmJS/TQfwnnTdjtKfcwuEPedmBc/erM6hBm4QYlffToyAnXpYif32ORrChP5rLXpiKx3pji9M3l4iKOFsGv4G34KvFo3MN6tJNkzeAvhT+Qul0wRnvrl0xVCehi17v/TJZe2baXW1uhtBp68VM/yb46je8fz3VE820Kb++U56TLdKLF3FLSx3KqRLLb9K5LVj18sRgjsFO7B1yOx6Rbm3jmBOOJBRa9hO51VthLw7NVFdTN6ey5edzcUujrbrtSxiFMIuQj83ThIxZPkBagcU9xQl6RlX6osw1UwA++erPK2L0XqlFi3WlnZSSMA7IAYVCrTZZuAtJIWvpASViwZpUt+UhGYGpc7ZrelOKPtnl6w="

before_script:
  - nvm install 4.2
  - npm install

script:
  # Search for PHP syntax errors.
  - find . \( -name '*.php' \) -exec php -lf {} \;


after_success:
  # Run npm build task.
  - run npm dist
  - bash ./bin/deploy.sh
